
services:
  rag_backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      rag_network:
        ipv4_address: 172.20.20.10

  rag_frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on: 
      - rag_backend
    networks:
      rag_network:
        ipv4_address: 172.20.20.11


networks:
  rag_network:
    driver: bridge
    ipam:
      config: 
       - subnet: 172.20.20.0/24